// <auto-generated />
using System;
using EnquiryRouting.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnquiryRouting.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260828144909_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("EnquiryRoutingApi")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgentSkill", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("AgentId", "SkillId");

                    b.HasIndex("SkillId", "AgentId");

                    b.ToTable("AgentSkills", "EnquiryRoutingApi");
                });

            modelBuilder.Entity("EnquiryRouting.Api.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Agents", "EnquiryRoutingApi");
                });

            modelBuilder.Entity("EnquiryRouting.Api.Entities.AgentLanguage", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<int>("LanguageCode")
                        .HasColumnType("integer");

                    b.HasKey("AgentId", "LanguageCode");

                    b.HasIndex("LanguageCode", "AgentId");

                    b.ToTable("AgentLanguages", "EnquiryRoutingApi");
                });

            modelBuilder.Entity("EnquiryRouting.Api.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnquiryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SenderType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnquiryId", "DateTimeCreated");

                    b.ToTable("ChatMessages", "EnquiryRoutingApi");
                });

            modelBuilder.Entity("EnquiryRouting.Api.Entities.Enquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DateTimeClosed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LanguageCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Enquiries", "EnquiryRoutingApi");
                });

            modelBuilder.Entity("EnquiryRouting.Api.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills", "EnquiryRoutingApi");
                });

            modelBuilder.Entity("EnquirySkill", b =>
                {
                    b.Property<Guid>("EnquiryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("EnquiryId", "SkillId");

                    b.HasIndex("SkillId", "EnquiryId");

                    b.ToTable("EnquirySkills", "EnquiryRoutingApi");
                });

            modelBuilder.Entity("AgentSkill", b =>
                {
                    b.HasOne("EnquiryRouting.Api.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnquiryRouting.Api.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnquiryRouting.Api.Entities.AgentLanguage", b =>
                {
                    b.HasOne("EnquiryRouting.Api.Entities.Agent", null)
                        .WithMany("Languages")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnquiryRouting.Api.Entities.ChatMessage", b =>
                {
                    b.HasOne("EnquiryRouting.Api.Entities.Enquiry", null)
                        .WithMany("Messages")
                        .HasForeignKey("EnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnquiryRouting.Api.Entities.Enquiry", b =>
                {
                    b.HasOne("EnquiryRouting.Api.Entities.Agent", null)
                        .WithMany("Enquiries")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("EnquirySkill", b =>
                {
                    b.HasOne("EnquiryRouting.Api.Entities.Enquiry", null)
                        .WithMany()
                        .HasForeignKey("EnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnquiryRouting.Api.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnquiryRouting.Api.Entities.Agent", b =>
                {
                    b.Navigation("Enquiries");

                    b.Navigation("Languages");
                });

            modelBuilder.Entity("EnquiryRouting.Api.Entities.Enquiry", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
